### ISSUE TITLE
consider cypress for e2e testing

### ISSUE THREAD

**Issue by cironunes** [r31gN/nott#1]

**Comment by r31gN** [comment]
Wow, this new framework looks amazing. Did not know anything about it until this mention. I am baffled by the fact that it is not Selenium based. I would definitely love to try this in the project.

This raises the question though: if nott will be used as a starter for a company project (which is definitely a strong and basic use case of this project), wouldn't that lock the company into this e2e framework and immediately force them to support additional costs (see the pricing plans)? What are your thoughts on this @cironunes?

**Comment by cironunes** [comment]
That's a valid concern. However, I don't see it as a dealbreaker, as long as we make sure to make it easy to remove altogether. 

If we do like that, people that don't wanna use it can just configure another solution by themselves. WDYT?

**Comment by r31gN** [comment]
Ok, it makes sense. It will be easy to remove because it will only contain a handful of demo tests. However, this needs to be transparent in the docs. Including downsides for companies (paid). I'm closing this with the decision to integrate Cypress and I've created https://github.com/r31gN/nott/issues/12 for integration. Feel free to own the issue if you want. Cypress though will go alongside Jest + Enzyme which will be used for shallow testing React components + testing reducers/actions.
